# Generated by Django 5.2.9 on 2026-01-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                ("zipcode", models.CharField(max_length=10)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "foodbank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.foodbank",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField(auto_now_add=True)),
                ("zipcode", models.CharField(max_length=10)),
                ("household_size", models.IntegerField()),
                ("age_0_17", models.IntegerField(default=0)),
                ("age_18_30", models.IntegerField(default=0)),
                ("age_31_50", models.IntegerField(default=0)),
                ("age_51_plus", models.IntegerField(default=0)),
                ("first_visit_this_month", models.BooleanField(default=False)),
                (
                    "foodbank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.foodbank",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="visits.patron",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
    ]
