# Generated by Django 5.2.9 on 2026-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="age_0_18",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="visit",
            name="age_19_59",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="visit",
            name="age_60_plus",
            field=models.IntegerField(default=0),
        ),
    ]
