# Generated by Django 5.2.9 on 2026-01-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_visit_age_0_18_visit_age_19_59_visit_age_60_plus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="age_0_17",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="age_18_30",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="age_31_50",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="age_51_plus",
        ),
    ]
