# Generated by Django 5.2.9 on 2026-01-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_remove_visit_age_0_17_remove_visit_age_18_30_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patron",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="patron",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patron",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
