# Generated by Django 5.2.9 on 2026-01-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0004_alter_patron_options_patron_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="patron_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="patron_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="patron_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
