# Generated by Django 5.2.9 on 2026-01-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0005_visit_patron_address_visit_patron_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patron",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
