# Generated by Django 5.2.9 on 2026-01-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0006_patron_comments_visit_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="patron",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patron",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
