# Generated by Django 5.2.9 on 2026-01-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0007_patron_city_patron_state_visit_city_visit_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="is_food_truck",
            field=models.BooleanField(default=False),
        ),
    ]
