# Generated by Django 5.2.9 on 2026-01-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0008_visit_is_food_truck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="visit_date",
            field=models.DateField(),
        ),
    ]
