# Generated by Django 5.2.9 on 2026-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_registrationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodbank",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
