# Generated by Django 5.2.9 on 2026-01-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_foodbank_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceZipcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zipcode", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "foodbank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_zipcodes",
                        to="accounts.foodbank",
                    ),
                ),
            ],
            options={
                "ordering": ["zipcode"],
                "unique_together": {("foodbank", "zipcode")},
            },
        ),
    ]
