# Generated by Django 5.2.9 on 2026-01-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_servicezipcode"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="servicezipcode",
            unique_together=set(),
        ),
    ]
