# Generated by Django 5.2.9 on 2026-01-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_servicezipcode_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodbank",
            name="food_truck_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
