# Generated by Django 5.2.9 on 2026-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_foodbank_food_truck_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodbank",
            name="timezone",
            field=models.CharField(default="America/Los_Angeles", max_length=50),
        ),
    ]
