# Generated by Django 5.2.9 on 2026-01-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_foodbank_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodbank",
            name="allow_anonymous",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="foodbank",
            name="allow_by_name",
            field=models.BooleanField(default=True),
        ),
    ]
