# Generated by Django 5.2.9 on 2026-01-15 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_foodbank_allow_anonymous_foodbank_allow_by_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodbankOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="foodbank",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent organization, if part of a larger network",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_foodbanks",
                to="accounts.foodbankorganization",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.foodbankorganization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
