# Generated by Django 5.2.9 on 2026-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_foodbankorganization_foodbank_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodbankorganization",
            name="contact_email",
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="state",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="foodbankorganization",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
