# Generated by Django 5.2.9 on 2026-01-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_foodbankorganization_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodbank",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent organization, if part of a larger network",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="foodbanks",
                to="accounts.foodbankorganization",
            ),
        ),
    ]
