# Generated by Django 5.2.9 on 2026-01-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_foodbank_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodbankorganization",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
