# Generated by Django 5.2.9 on 2026-01-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_foodbankorganization_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodbank",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Tell people about your food bank (shown on locations page)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="foodbank",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Show on public locations map"
            ),
        ),
        migrations.AddField(
            model_name="foodbank",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Auto-generated from address",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="foodbank",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Auto-generated from address",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Public description for your organization (shown on locations page)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Show on public locations map"
            ),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Auto-generated from address",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="foodbankorganization",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Auto-generated from address",
                max_digits=9,
                null=True,
            ),
        ),
    ]
