# Generated by Django 5.2.9 on 2026-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("baby_food", "Baby Food"),
                            ("shelf_stable", "Shelf-Stable"),
                            ("refrigerated", "Refrigerated"),
                            ("frozen", "Frozen"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                ("shelf_life_display", models.CharField(max_length=100)),
                ("shelf_life_min_days", models.IntegerField(blank=True, null=True)),
                ("shelf_life_max_days", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Food Item",
                "verbose_name_plural": "Food Items",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="resources_f_name_57a2f6_idx"),
                    models.Index(
                        fields=["category"], name="resources_f_categor_45408a_idx"
                    ),
                ],
            },
        ),
    ]
